### ISSUE TITLE
Is ios-core sufficient to do local sqlite ORM?

### ISSUE THREAD

**Issue by limulidae** [Siminov/ios-core#2]
Hi,
I would like to build an android + an iphone app.
we need to save some data to local db.
I glanced some documents, looks like I only need android-core and ios-core?

Can I do the same thing in iphone with only ios-core?
http://siminov.com/developer-portal/core/android/sample-saving.html

Thanks,

**Comment by Siminov** [comment]
Hi Limulidae:

Siminov Framework is build on a concept of <b>Build Once And Run Anywhere</b>. The same configuration files which you define for Android, will work for iOS too. 

It has same Architecture,  API's, Functionality on all the major platforms (Android, iOS, Windows OS, and Windows Phone OS). If you are familiar with Siminov on one platform then it will be very easy to port the same on any of the platform.

Yes, you can do the same thing on iOS using ios-core. But currently ios-core is in its last stage of development, and will be released by end of this month, and its documentation on or before 15th March.

Let us know if you have any doubts.

Thanks

**Comment by Siminov** [comment]
Hi Limulidae:

We have released iOS Core Version 1.0 few days back. You can download it from <a href="http://siminov.com/build.html">Builds</a>, and its documentation is available at <a href="http://siminov.com/developer-portal/core/ios/home.html">iOS Core Documentation</a>

Let us know if you face any issues while configuring your app. 

Looking forward to hear from you.

Thanks
